version: 2.1

jobs:
  lint-and-test:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip install pdm
      - run: pdm install
      - run: pdm run black --check .
      - run: pdm run pytest --cov
  build-and-push:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u digyx -p $DOCKERHUB_PASSWORD
      - run: docker build -t digyx/ciel:$CIRCLE_BUILD_NUM .
      - run: docker push digyx/ciel:$CIRCLE_BUILD_NUM

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-push:
          requires:
            - lint-and-test
